title: Strange Security
description: Exploring the Strangeness of Security !
theme: jekyll-theme-hacker # or the name of another theme you want to use
url: https://strange-0.github.io # replace with your actual GitHub Pages URL
baseurl: # if your site is hosted at a subpath (e.g. https://your-username.github.io/my-site)
favicon: /favicon.ico

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


---
connect:
  twitter: "https://twitter.com/your_username"
  medium: "https://medium.com/@your_username"
  linkedin: "https://www.linkedin.com/in/your_username"
  hackthebox: "https://www.hackthebox.eu/profile/your_username"
  tryhackme: "https://tryhackme.com/p/your_username"
---
