title: Strange Security
description: Sharing my journey as a hacker and penetration tester through insightful articles and blogs on cybersecurity. Learn from my experiences, challenges, and discoveries in the world of hacking and stay up to date with the latest trends and techniques.
theme: jekyll-theme-hacker # or the name of another theme you want to use
url: https://strange-0.github.io # replace with your actual GitHub Pages URL
baseurl: # if your site is hosted at a subpath (e.g. https://your-username.github.io/my-site)

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
